source 'https://rubygems.org'

ruby '>= 3.2'

# Web
gem 'sinatra', '~> 4.1'
gem 'sinatra-contrib', '~> 4.1'
gem 'puma', '~> 6.4'
gem 'rackup', '~> 2.1'

# Database
gem 'sequel', '~> 5.86'
gem 'pg', '~> 1.5'

# Datadog APM
gem 'datadog', '~> 2.0'
